#!/usr/bin/env bash
# Filter logs through a color highlighter.  Mostly intended for typical
# Java-format logs (log4j, etc), but probably works on other logs too.
#
# Get the latest version at https://github.com/fardaniqbal/misc-utils/.
set -uo pipefail
COLORLOG_VERSION="0.1.1"
self="$(basename "$0")"

# Effectively don't match any stack frame by default.
COLORLOG_HL_STACK_FRAME="${COLORLOG_HL_STACK_FRAME:-^$}"

help() {
  cat <<EOF
Usage: $self [OPTIONS] [FILE]

Colorize logs read from FILE (if given) or standard input (if FILE is not
given and standard input is not a terminal.)  If FILE is \`-\`, then read
from standard input even if it's a terminal.

This is primarily intended for typical Java-format logs (log4j, etc), but
will likely work on other similarly-formatted logs too.

EXAMPLES:
- Tail Tomcat logs with pizzazz:
      tail -f catalina.out | colorlog
- Same, but extra highlights for stack frames from \`com.mycompany\`:
      tail -f catalina.out | colorlog -s 'com\\.mycompany'

OPTIONS:
-h, --help
  Show this message and exit.
-s=REGEX, --hl-stack-frame=REGEX
  For stack traces, highlight stack trace lines matching REGEX.  Overrides
  COLORLOG_HL_STACK_FRAME environment variable.
-V, --version
  Show version number and exit.

ENVIRONMENT VARIABLES:
- COLORLOG_HL_STACK_FRAME: highlight stack trace lines matching the regex
    specified by this variable.  Overridden by -s/--hl-stack-frame.

Get the latest version at https://github.com/fardaniqbal/misc-utils/.
EOF
}

# Scan command line options/args.
while [ $# -gt 0 ]; do
  opt="${1%%=*}"
  optarg="${1#*=}"
  shiftarg=''
  if [ "$opt" = "$1" ]; then
    optarg="${2:-}"
    shiftarg=shift
  fi
  case "$opt" in
    -h|--help) help; exit 0;;
    -s|--hl-stack-frame)
      COLORLOG_HL_STACK_FRAME="$optarg"
      $shiftarg;;
    -V|--version)
      printf 'colorlog %s\n' "$COLORLOG_VERSION"
      exit 0;;
    -) break;;
    --) shift; break;;
    -*)
      printf 'ERROR: unrecognized option %s.\n' "'$opt'" >&2
      printf 'Run `%s --help` for usage info.\n' "$self" >&2
      exit 2;;
    *) break;;
  esac
  shift
done

# Main log highlighter.
command -v gawk >/dev/null 2>&1 && awk() { gawk "$@"; }
main() {
  awk \
    -v re_spc=$'[ \t]' \
    -v vtreset=$'\e[0m' \
    -v vtred=$'\e[31m' -v vtredbr=$'\e[91m' \
    -v vtgrn=$'\e[32m' -v vtgrnbr=$'\e[92m' \
    -v vtyel=$'\e[33m' -v vtyelbr=$'\e[93m' \
    -v vtblu=$'\e[34m' -v vtblubr=$'\e[94m' \
    -v vtpur=$'\e[35m' -v vtpurbr=$'\e[95m' \
    -v vtcya=$'\e[36m' -v vtcyabr=$'\e[96m' \
    -v vtwht=$'\e[37m' -v vtwhtbr=$'\e[97m' \
    -v vtemp=$'\e[38;2;220;230;255m\e[1m'   \
    -v vtbold=$'\e[1m'        -v vtnobold=$'\e[22m'         \
    -v vtdim=$'\e[2m'         -v vtnodim=$'\e[22m'          \
    -v vtitalic=$'\e[3m'      -v vtnoitalic=$'\e[23m'       \
    -v vtunderline=$'\e[4m'   -v vtnounderline=$'\e[24m'    \
    -v vtundercurl=$'\e[4:3m' -v vtnoundercurl=$'\e[24m'    \
    -v vtundercurlcolor=$'\e[4:3m\e[58:2::240:45:15m'       \
    -v vtnoundercurlcolor=$'\e[59m' \
    -v vtblink=$'\e[5m'       -v vtnoblink=$'\e[25m'        \
    -v vtinverse=$'\e[7m'     -v vtnoinverse=$'\e[27m'      \
    -v vthidden=$'\e[8m'      -v vtnohidden=$'\e[28m'       \
    -v vtstrikethru=$'\e[9m'  -v vtnostrikethru=$'\e[29m'   \
    -v COLORLOG_HL_STACK_FRAME="$( # escape backslashes in this var
      sed -E 's#\\#\\\\#g' <<<"$COLORLOG_HL_STACK_FRAME")"  \
    -f <(cat <<'EOF'
function rgbfg(r,g,b) { return "\033[38;2;" r ";" g ";" b "m" }
function rgbbg(r,g,b) { return "\033[48;2;" r ";" g ";" b "m" }
BEGIN {
  re_date_letters="[0-9]{1,2}[ -][A-Za-z]{3},?|[A-Za-z]{3}[ -][0-9]{1,2},?"
  re_date_numbers="[0-9]{2}[ /-][0-9]{2}"
  re_date="(([0-9]{2}|[0-9]{4})[ -](" re_date_letters "))"
  re_date=re_date "|((" re_date_letters ") ?,?[ -]?([0-9]{2}|[0-9]{4}))"
  re_date=re_date "|([0-9]{4}[ /-]" re_date_numbers ")|(" re_date_numbers "[ /-][0-9]{4})"
  re_date="(" re_date ")"
  re_time="[0-9]{1,2}:[0-9]{2}:[0-9]{2}([.,][0-9]*)?[A-Z]?"
  re_time=re_time re_spc "*([Aa][Mm]|[Pp][Mm]|([+-][0-9]{2}(:?[0-9]{2})?))?"
  re_ts="(" re_date "( *[Tt/-]? *))?(" re_time ")"
  re_ts="(\\[?" re_spc "*\\<" re_ts "\\>" re_spc "*\\]?)"

  re_sev="(\\<(TRACE|DEBUG|INFO|WARN(ING)?|ERROR|FATAL|SEVERE)\\>)"
  re_sev="(\\[?" re_spc "*" re_sev re_spc "*\\]?)"
  re_sev="(" re_sev "|\\[(TRC|DBG|INF|WRN|ERR|FTL|SVR|SEV)\\])"

  re_brkt_0="\\[[^][]*\\]"
  re_brkt=re_brkt_0 re_spc "*"
  for (i = 0; i < 4; i++) {
    re_brkt_0="\\[[^][]*" re_brkt_0 "[^][]*\\]"
    re_brkt=re_brkt "|" re_brkt_0 re_spc "*"
  }
  re_thrd="(" re_brkt ")"
  re_class="([A-Za-z0-9_$./\\\\]+)"
  re_num="(\\<([0-9]+(\\.[0-9]*)*([EePp][+-]?[0-9]+)?|0[Xx][0-9A-Fa-f]+|0[Bb][01]+)\\>)"
  re_punc="[][|&^~!=<>(){}?:;*/%.,\\\\+-]"

  sevcolor=vtwhtbr vtnodim; msgcolor=vtwhtbr vtnodim;
}

# Match REGEX against STR, skipping any substrings previously matched on
# the current record (as tracked by `starts` and `lens` global arrays.)  If
# match is found, insert the match's start pos, length, and given COLOR
# into `starts`, `lens`, and `colors`, respectively.
# Return start pos of match if found, or 0 if not found.
function hlmatch(str, regex, color,     start, len, i, j, p0, p1) {
  for (i=1; i<=hlcount; i++) {
    p0=starts[i]+lens[i]
    if (i+1 <= hlcount) { p1=starts[i+1] }
    else                { p1=length(msg)+1 }
    if (match(substr(msg, p0, p1-p0), regex)) {
      # Insert new start/len/color into arrays sorted by start index.
      start=RSTART+p0-1; len=RLENGTH
      hlcount++
      for (; i<hlcount; i++) {
        if (starts[i] > start) {
          for (j=hlcount; j>i; j--) {
            starts[j]=starts[j-1]
            lens[j]=lens[j-1]
            colors[j]=colors[j-1]
          }
          break
        }
      }
      starts[i]=start
      lens[i]=len
      colors[i]=color
      return start
    }
  }
  return 0
}

{
  starts[1]=1; lens[1]=0; colors[1]=msgcolor
  hlcount=1
  msg=$0

  # Determine how to color base on whether line has timestamp, severity,
  # and/or stack trace elements.
  if (match(toupper(msg), re_sev)) {
    havesev=1; sevstart=RSTART; sevlen=RLENGTH
  }

  # Give different colors to different severities.
  if (havesev) {
    sev=toupper(substr(msg, sevstart, sevlen))
    if (sev ~ /\<TRACE\>/ || sev ~ /\[TRC\]/) {
      sevcolor=msgcolor=vtdim vtcya;
    } else if (sev ~ /\<DEBUG\>/ || sev ~ /\[DBG\]/) {
      sevcolor=msgcolor=vtdim vtblubr;
    } else if (sev ~ /\<INFO\>/ || sev ~ /\[INF\]/) {
      sevcolor=vtnodim vtgrnbr; msgcolor=vtwhtbr vtnodim
    } else if (sev ~ /\<WARN(ING)?\>/ || sev ~ /\[WRN\]/) {
      sevcolor=msgcolor=vtnodim vtyel
    } else if (sev ~ /\<ERROR\>/ || sev ~ /\[ERR\]/) {
      sevcolor=msgcolor=vtnodim vtredbr
    } else if (sev ~ /\<(FATAL|SEVERE)\>/ || sev ~ /\[(FTL|SVR|SEV)\]/) {
      sevcolor=msgcolor=vtdim vtredbr
    }
  }

  # Highlight stack traces.
  if (match(msg,
      "^(" re_spc "*(at )?)(([a-zA-Z0-9_$]+\\.)*)([a-zA-Z0-9_$]+\\.)" \
      "([a-zA-Z0-9_<>$]+" re_spc "*)" \
      "(\\()([^():]*)?(:)?([^()]*)?(\\))(.*)$", arr)) {
    pkgcolor=vtdim vtredbr
    if (match(arr[0], COLORLOG_HL_STACK_FRAME)) pkgcolor=vtnodim
    print \
      vtdim vtredbr arr[1] pkgcolor arr[3] \
      vtyel         arr[5] vtblu    arr[6]  vtwht arr[7]  vtwht arr[8]  \
      vtwht         arr[9] vtcya    arr[10] vtwht arr[11] \
      msgcolor      arr[12]
    next
  }

  hlmatch(msg, re_ts, vtwht vtdim)
  if (havesev) hlmatch(toupper(msg), re_sev, sevcolor)
  hlmatch(msg, re_thrd, vtdim vtblu)
  hlmatch(msg, re_class, vtpur)
  while (hlmatch(msg, re_num, vtred)) continue
  while (hlmatch(msg, re_punc, vtcyabr)) continue
  while (hlmatch(msg, re_thrd, vtdim vtblu)) continue

  for (i=1; i<=hlcount; i++) {
    p0=starts[i]; p1=starts[i]+lens[i]
    if (i+1 <= hlcount) { p2=starts[i+1] }
    else                { p2=length(msg)+1 }
    printf("%s", colors[i] substr(msg, p0, p1-p0))
    printf("%s", msgcolor substr(msg, p1, p2-p1))
  }
  printf("\n")
}
EOF
  )
}

# Be helpful if stdin is a terminal and no FILE args were given.
if [ $# -eq 0 ] && [ -t 0 ]; then help >&2; exit 2; fi
if [ $# -gt 1 ]; then
  printf 'ERROR: invalid arguments.\n' >&2
  printf 'Run `%s --help` for usage info.\n' "$self" >&2
  exit 2
fi

# Ready to go!
if [ $# -eq 0 ] || [ "$1" = "-" ]; then main; exit $?; fi
main < "$1"
